---
title: ""
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<style>
h4, h5{
  color: SeaGreen ;
  font-family: Verdana;
}

p {
  font-family: Verdana;
  font-size: 13px;
}

.graybg {
  background-color: WhiteSmoke  ;
}

.withPadding{
  padding:2%;
}
  
.center{
  display: block;
  margin-left: auto;
  margin-right: auto;
  width: 50%;margin-left: auto;
  margin-right: auto;
  width: 50%;
}

.select-style {
    border: 1px solid #ccc;
    width: 400px;
    border-radius: 3px;
    overflow: hidden;
    background: #fafafa url("img/icon-select.png") no-repeat 90% 50%;
}

.select-style select {
    padding: 5px 8px;
    width: 130%;
    border: none;
    box-shadow: none;
    background: transparent;
    background-image: none;
    -webkit-appearance: none;
}

.select-style select:focus {
    outline: none;
}
</style>

<h4 class="my-4">DROP US A LINE</h4>
<h5 class="my-4">Types of Inquiry: </h5>
<div class="select-style">
    <select>
      <option value="o1">Franchising Inquiry Philippines</option>
      <option value="o2">Franchising Inquiry International</option>
      <option value="o3">Sponsorship Request</option>
      <option value="o4">Product/Store Complaint</option>
      <option value="o5">Product/Store Commendation</option>
      <option value="o6">Suggestion</option>
    </select>
  </div>

<h5 class="my-4">Your Name </h5>
<div class="withPadding">
  <input type="text" value="Mickey">
</div>

<h5 class="my-4">Your Email </h5>
<h5 class="my-4">Your Comment </h5>